### PR TITLE
Use more docstring

### PR DESCRIPTION
**Pull request by sbrunner**
To improve compatibility with IDE and documentation generator
Render TypedDict as a class if possible
Respect PEP-258: https://peps.python.org/pep-0258/

Fix: #134

### CODE REVIEW

**Comment by sbrunner** [comment]
@bollwyvl, @Samrose-Ahmed does it look good?

**Comment by bollwyvl** [comment]
I think i tried triple-quotes, and they were not picked up by sphinx-autodoc, not sure about the language servers...

**Comment by sbrunner** [comment]
As it's written here, it should work...
https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#directive-autoproperty
In VSCode it's working :-)

**Comment by bollwyvl** [comment]
> or in a docstring after the definition.

oof. didn't know about that... seems like a strange choice. but if it's working, go for it. 

One additional piece: if the comment + quotes would fit on a (configurable) line length, it might be nice to get:

```py
x: str
"""the horizontal position"""
```

instead of

```py
x: str
"""
the horizontal position
"""
```

but perhaps something like `docformatter` can do this after the fact automatically.

**Comment by sbrunner** [comment]
Thanks, @bollwyvl, I update it :-)

**Review by arnaud-morvan — APPROVED** [review]
LGTM

**Pull request merged**
